apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        nginx: test
    spec:
      containers:
      - mame: nginx-cont
        image: nginx
  selector:
    matchLabels:
      nginx: test